apiVersion: v1
kind: Service
metadata:
  name: eira-backend-service
  labels:
    app: eira-backend
spec:
  selector:
    app: eira-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
