apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eira-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: eira.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: eira-backend-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eira-frontend-service
            port:
              number: 80
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: eira-backend-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eira-frontend-service
            port:
              number: 80
