name: "Gitleaks Secrets Scan"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        with:
          args: detect --source . --no-git --report-format sarif --report-path gitleaks-results.sarif

      - name: Upload Gitleaks report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'gitleaks-results.sarif'
          category: 'gitleaks'