name: "Gitleaks Secrets Scan"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  scan:
    name: Secrets Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Normalize SARIF Name
        if: always()
        run: mv results.sarif gitleaks-results.sarif || echo 'SARIF file absent.'

      - name: Upload Gitleaks report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'gitleaks-results.sarif'
          category: 'gitleaks'